### ISSUE TITLE
Setting null as array value

### ISSUE THREAD

**Issue by mtharrison** [janl/node-jsonpointer#25]
I was expecting to be able to set `null` as an array item. Instead it sets the item to `undefined`:

```javascript
var obj = { foo: 1, bar: { baz: 2}, qux: [3, 4, 5]};
jsonpointer.set(obj, '/qux/1', null);

{ foo: 1, bar: { baz: 2 }, qux: [ 3, , 5 ] }       // result
{ foo: 1, bar: { baz: 2 }, qux: [ 3, null, 5 ] }   // expected
```

Is this the intended behaviour?

**Comment by marcbachmann** [comment]
I think that's something not defined in the spec.
So as long as there is no test test for it, we didn't specify that behavior.

**Comment by marcbachmann** [comment]
There's an open pr that might fix it.

**Comment by mtharrison** [comment]
I tried with your branch `performance-improvements` and the behaviour is the same. If you're open to changing it, I'd be happy to take a stab at a PR?

**Comment by marcbachmann** [comment]
Ok. that line is the problem: https://github.com/marcbachmann/node-jsonpointer/blob/performance-improvements/jsonpointer.js#L42

I think I didn't change that because I didn't want to change the behavior.
We can change that but it needs a major version bump.
I'd accept a pr that builds on my one. Can you review it at the same time? :grin:

**Comment by mtharrison** [comment]
Sure, give me a few days and I'll look into it :smile:
